name: demo
root: <%= ENV["PWD"] %>

# Runs on project start, always
on_project_start: brew services start zookeeper; brew services start kafka

windows:
  - run:
      layout: tiled
      panes:
        - cd statusconsumer; python3 app.py
        - cd images-from-postapi; source .envrc; go run src/images-from-postapi/main.go
        - cd objectdetector; python3 app.py
        - cd streamingdemo; source .envrc; cd src/streamingdemo; go run main.go
        - sleep 5; cd imagesfromopencv-to-postapi; POST_ENDPOINT=http://localhost:8000/image CAMERA=opencv python3 app.py
